# Generated by Django 3.0.1 on 2020-03-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levfiv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profle_pic',
            new_name='profile_pic',
        ),
    ]
